### ISSUE TITLE
Parameters window is uneditable

### ISSUE THREAD

**Issue by sdbernard** [jdugge/ClipToHemisphere#2]
Using qgis 2.8 on Mac OS 10.9.5 the parameter window is empty with no way of adding lat/long

![image](https://cloud.githubusercontent.com/assets/2511348/12531081/76d22666-c1ea-11e5-9349-16beac56182c.png)

**Comment by jdugge** [comment]
Thanks for the report! I'll see if I can reproduce this on a MacBook tomorrow

**Comment by jdugge** [comment]
Tested with QGIS 2.8 and 2.12 on Mac OS X 10.10, and the issue doesn't appear there. Do other tools from the Processing Toolbox work on your system? Can you check if it works in the Graphical Modeller instead of directly from the Toolbox?
