### ISSUE TITLE
Please consider moving it under Processing

### ISSUE THREAD

**Issue by pcav** [jdugge/ClipToHemisphere#5]
You'll save coding the interface, and the user will be able to integrate this into more complex workflows, having iterations, and much more.
Ask @volaya for howto, or have a look to other Processing plugins.

**Comment by jdugge** [comment]
I'm not sure I understand: This plugin already is a Processing plugin. It appears in the Processing toolbox and can be included in models in the Graphical Modeler.

**Comment by pcav** [comment]
Sorry, overlooked this
